server:
  port: 8086
  compression:
    enabled: true
spring:
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/cp_master
    username: root
    password:

  jackson:
    serialization:
      fail-on-empty-beans: false

  queries:
    users-query: select user_name, password, status from user where user_name=?
    roles-query: select u.user_name, a.type from user u join role r left join role_permission_rights rpr on rpr.role_id = r.id left join role_permission_rights_api_rights rprar on rprar.role_permission_rights_id=rpr.id left join url_api a on rprar.api_rights_id = a.id where (a.type is not null and u.user_name=? );

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

logging:
  level:
    org:
      hibernate:
        SQL: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    refresh:
      enabled: true
    restart:
      enabled: true

file:
  upload-directory: Z:/