server:
  port: 8086
  compression:
    enabled: true
spring:
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
        hibernate:
              enable_lazy_load_no_trans: true
  datasource:
    url: jdbc:mysql://localhost:3306/cp_master
    username: root
    password: root
  mail:
    username: sbsolutionstest@gmail.com
    password: testsbsolutions123

  jackson:
    serialization:
      fail-on-empty-beans: false

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

logging:
  level:
    org:
      hibernate:
        SQL: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    refresh:
      enabled: true
    restart:
      enabled: true

file:
  upload-directory: C:/
