spring:
  datasource:
    url: jdbc:sqlserver://150.107.205.62:1433;database=las_v2
    username: sa
    password: sbdb@141

app:
  datasource:
    cbs:
      url: jdbc:sqlserver://150.107.205.62:1433;database=cbs
      username: sa
      password: sbdb@141
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    tableName: cbs_group
