spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=megav2_test
    username: sa
    password: sbdb@141

bank:
  affiliateId: mega
  name: Mega Bank Nepal Limited.
  website: http://www.megabanknepal.com/

product:
  las: true
  offerletter: true
  memo: false
  account: false
  eligibility: true
  dms: false
  nepTemplate: false
  cadLiteVersion: false
  loanApprovalHierarchyLevel: LOAN #DEAFULT = Disable Approval Hierarchy, LOAN_TYPE = Enable Approval Hierarchy for loan type, LOAN = Enable Role Hierarchy for loan
  fullCad: true #only fullCad should not be enable. you should enable offerLetter also
  cbsEnable: false
  checklistLiteVersion: true
  microLoan: true

#this feature is enabled if cbsEnable is set true
#url : remote server url
app:
  datasource:
    cbs:
      url: jdbc:sqlserver://150.107.205.62:1433;database=cbs
      username: sa
      password: sbdb@141
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    tableName: cbs_group
    uniqueKey: obligor

