server:
  port: 8086
  compression:
    enabled: true
spring:
  application:
    name: las
  jmx:
    default-domain: las
  profiles:
    active: dev
  thymeleaf:
    enabled: true
    check-template-location: true
    prefix: classpath:/webapp/

  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    serialization:
      fail-on-empty-beans: false

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

logging:
  level:
    org:
      hibernate:
        SQL: error

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    refresh:
      enabled: true
    restart:
      enabled: true

file:
  upload-directory: C:/

bank:
  name: SB Solutions Pvt Ltd
  website: http://www.sbsolutionsnepal.com.np/

mailproperty:
  additionalHeaders:
    mail:
      transport:
        protocol: smtp
      smtp:
        auth: true
        starttls:
          enable: true
        socketFactory:
          class: javax.net.ssl.SSLSocketFactory
      debug: true

product:
  las: true
  offerletter: true
  memo: false
  account: true
  eligibility: true
  dms: false
  nepTemplate: true
  loanApprovalHierarchyLevel: LOAN_TYPE #DEAFULT = Disable Approval Hierarchy, LOAN_TYPE = Enable Approval Hierarchy for loan type, LOAN = Enable Role Hierarchy for loan
