package com.sb.solutions.api.approvallimit.emuns;

public enum Authorities {
     ROLE_AUTHENTICATED,
    ROLE_ADMINISTRATOR,
    ROLE_RELATIONSHIP_MANAGER,
    ROLE_SENIOR_RELATIONSHIP_MANAGER,
    ROLE_BRANCH_MANAGER,
    ROLE_REGIONAL_MANAGER,
    ROLE_CREDIT_RISK_OFFICER,
    ROLE_RISK_MANAGER,
    ROLE_MANAGER,
    ROLE_SENIOR_MANAGER,
    ROLE_ASSISTANT_GM,
    ROLE_DEPUTY_GM,
    ROLE_DEPUTY_CEO,
    ROLE_CEO,
    ROLE_BOD,
    ROLE_CA,
    ROLE_CREDIT_COMMITTEE
}
